---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tictake-web-backend
  minReplicas: 1
  maxReplicas: 30
  behavior:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 100Mi
