resources:
  - ../../../base/web-backend
  - ../../../base/web-frontend
  - ../../../base/redis
  - hpa.yaml
  - ingressroute.yaml

replicas:
  - name: tictake-web-backend
    count: 1
  - name: tictake-web-frontend
    count: 1

configMapGenerator:
  - name: web-backend-config
    envs:
      - config/env.properties

secretGenerator:
  - name: web-backend-secret
    envs:
      - config/secret.properties
