kind: pipeline
type: docker
name: en

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello world

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: fr

steps:
  - name: greeting
    image: alpine
    commands:
      - echo bonjour monde

trigger:
  event:
    - pull_request
