---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictake-web-backend
  labels:
    app: web-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-backend
  template:
    metadata:
      labels:
        app: web-backend
    spec:
      containers:
        - name: web-backend
          image: ghcr.io/disam8853/tictake/web-backend:main
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: web-backend-config
