---
apiVersion: v1
kind: Service
metadata:
  name: tictake-web-backend
  labels:
    app: web-backend
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: web-backend
