---
apiVersion: v1
kind: Service
metadata:
  name: tictake-api-user-activity
  labels:
    app: api-user-activity
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: api-user-activity
