resources:
  - ../../../base/api-ticket
  - hpa.yaml

replicas:
  - name: tictake-api-ticket
    count: 1

configMapGenerator:
  - name: api-ticket-config
    envs:
      - config/env.properties

secretGenerator:
  - name: bigtable-credential
    files:
      - config/google-credential.json
