---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-user-activity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tictake-api-user-activity
  minReplicas: 5
  maxReplicas: 50
  behavior:
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 300Mi
