resources:
  - ../../../base/api-user-activity
  - hpa.yaml

replicas:
  - name: tictake-api-user-activity
    count: 1

configMapGenerator:
  - name: api-user-activity-config
    envs:
      - config/env.properties

secretGenerator:
  - name: api-user-activity-secret
    envs:
      - config/secret.properties
