---
apiVersion: v1
kind: Service
metadata:
  name: tictake-web-frontend
  labels:
    app: web-frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: web-frontend
